
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import customtkinter as ctk
from customtkinter import *
from pathlib import Path
import os
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()
window_width = window.winfo_reqwidth()
window_height = window.winfo_reqheight()
position_right = int(window.winfo_screenwidth()/2 - window_width/2)
position_down = int(window.winfo_screenheight()/2 - window_height/2)

window.geometry("+{}+{}".format(position_right-400, position_down-300))

window.geometry("1181x708")
window.configure(bg = "#FFFFFF")

'''
CANVAS
'''
#canvas frame
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 708,
    width = 1181,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#canvas image background
canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("help_image_1.png"))
image_1 = canvas.create_image(
    590.0,
    354.0,
    image=image_image_1
)

#canvas TEXT
canvas.create_text(
    111.0,
    46.0,
    anchor="nw",
    text="WELCOME\nWORD SEARCH GENERATOR\n",
    fill="#BD946F",
    font=("Nunito Bold", 32 * -1)
)
canvas.create_text(
    111.0,
    174.0,
    anchor="nw",
    text="ABOUT\n\nThis is a word search generator that\ncreates a word search puzzle from a list\nof words. The words can be placed in any\norientation, and in any direction.\n\nThe puzzle can be printed or saved as a\nPDF file.\n",
    fill="#BD946F",
    font=("Nunito Bold", 32 * -1)
)
'''
DEF
'''
def run_home():
    window.destroy()
    # string = "python + file name"
    os.system("python menu.py")

'''
BUTTONS
'''
#canvas BUTTON 1: HOME
button_image_1 = PhotoImage(
    file=relative_to_assets("help_button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=run_home,
    relief="flat"
)
button_1.place(
    x=7.0,
    y=0.0,
    width=35.0,
    height=35.0
)


window.resizable(False, False)
window.mainloop()
