
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window_width = window.winfo_reqwidth()
window_height = window.winfo_reqheight()
position_right = int(window.winfo_screenwidth()/2 - window_width/2)
position_down = int(window.winfo_screenheight()/2 - window_height/2)

window.geometry("+{}+{}".format(position_right, position_down-100))
window.geometry("563x275")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 275,
    width = 563,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("alert_image_1.png"))
image_1 = canvas.create_image(
    281.0,
    137.0,
    image=image_image_1
)

canvas.create_text(
    117.0,
    101.0,
    anchor="nw",
    text="! YOU MUST TO TYPE TOPIC NAME",
    fill="#A97E54",
    font=("Nunito Bold", 20 * -1)
)

def ok_button():
    window.destroy()

button_image_1 = PhotoImage(
    file=relative_to_assets("alert_button_1.png"))
button_1 = Button(
    image=button_image_1,
    text="OK",
    compound="center",  # Add this line
    borderwidth=0,
    highlightthickness=0,
    command=ok_button,
    relief="flat",
    font=("Nunito Bold", 20 * -1),  # Change the font size here,
    fg = "#A97E54",
)
button_1.place(
    x=233.0,
    y=143.0,
    width=97.0,
    height=37.0
)

canvas.create_text(
    266.0,
    148.0,
    anchor="nw",
    text="OK",
    fill="#A97E54",
    font=("Nunito Bold", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
