
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os
# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk 
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class PlayAgainMenu:

    def __init__(self, master):
        self.master = master
        self.toplevel = tk.Toplevel(master, height = 563, width = 275, bg="#FFFFFF")
        self.canvas = tk.Canvas(
            self.toplevel,
            bg = "#FFFFFF",
            height = 275,
            width = 563,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.pack()
        self.pl_image_image_1 = PhotoImage(
            file=relative_to_assets("pl_image_1.png"))
        self.pl_image_1 = self.canvas.create_image(
            281.0,
            137.0,
            image=self.pl_image_image_1
        )
        self.pl_button_image_1 = PhotoImage(
            file=relative_to_assets("pl_button_1.png"))
        self.pl_button_1 = Button(
            self.toplevel,
            image=self.pl_button_image_1,
            text="YES",
            compound="center",  # Add this line
            borderwidth=0,
            highlightthickness=0,
            command=self.run_menu,
            relief="flat",
            font=("Nunito Bold", 20 * -1),  # Change the font size here
            fg="#A97E54"  # Change the font color here
        )
        self.pl_button_1.place(
            x=166.0,
            y=147.0,
            width=97.0,
            height=37.0
        )

        self.pl_button_image_2 = PhotoImage(
            file=relative_to_assets("pl_button_2.png"))
        self.pl_button_2 = Button(
            self.toplevel,
            image=self.pl_button_image_2,
            text="NO",
            compound="center",  # Add this line
            borderwidth=0,
            highlightthickness=0,
            command=self.run_play,
            relief="flat",
            font=("Nunito Bold", 20 * -1),  # Change the font size here
            fg="#A97E54"  # Change the font color here
        )
        self.pl_button_2.place(
            x=295.0,
            y=147.0,
            width=97.0,
            height=37.0
        )

        self.canvas.create_text(
            143.0,
            95.0,
            anchor="nw",
            text="ARE YOU SURE PLAY AGAIN?",
            fill="#A97E54",
            font=("Nunito Bold", 20 * -1)
        )

    #YES
    def run_menu(self):
        self.toplevel.destroy()
        self.master.destroy()
        os.system('python menu.py')
    def run_play(self):
        self.toplevel.destroy()



# window.geometry("563x275")
# window.configure(bg = "#FFFFFF")


# canvas = Canvas(
#     window,
#     bg = "#FFFFFF",
#     height = 275,
#     width = 563,
#     bd = 0,
#     highlightthickness = 0,
#     relief = "ridge"
# )

# #YES
# def run_menu():
#     window.destroy()
#     os.system('python menu.py')
#     return 0

# #NO
# def run_play():
#     window.destroy()

# def run():
#     os.system("python pl.py")
#     if run_menu() == 0:
#         return 0

# canvas.place(x = 0, y = 0)
# pl_image_image_1 = PhotoImage(
#     file=relative_to_assets("pl_image_1.png"))
# pl_image_1 = canvas.create_image(
#     281.0,
#     137.0,
#     image=pl_image_image_1
# )
# pl_button_image_1 = PhotoImage(
#     file=relative_to_assets("pl_button_1.png"))
# pl_button_1 = Button(
#     image=pl_button_image_1,
#     text="YES",
#     compound="center",  # Add this line
#     borderwidth=0,
#     highlightthickness=0,
#     command=run_menu,
#     relief="flat",
#     font=("Nunito Bold", 20 * -1),  # Change the font size here
#     fg="#A97E54"  # Change the font color here
# )
# pl_button_1.place(
#     x=166.0,
#     y=147.0,
#     width=97.0,
#     height=37.0
# )

# pl_button_image_2 = PhotoImage(
#     file=relative_to_assets("pl_button_2.png"))
# pl_button_2 = Button(
#     image=pl_button_image_2,
#     text="NO",
#     compound="center",  # Add this line
#     borderwidth=0,
#     highlightthickness=0,
#     command=run_play,
#     relief="flat",
#     font=("Nunito Bold", 20 * -1),  # Change the font size here
#     fg="#A97E54"  # Change the font color here
# )
# pl_button_2.place(
#     x=295.0,
#     y=147.0,
#     width=97.0,
#     height=37.0
# )

# canvas.create_text(
#     143.0,
#     95.0,
#     anchor="nw",
#     text="ARE YOU SURE PLAY AGAIN?",
#     fill="#A97E54",
#     font=("Nunito Bold", 20 * -1)
# )
# window.resizable(False, False)
# window.mainloop()
